NumPy is used to handle n-dimensional array and performing numerical computations on them.

For example, say we want to do matrix multiplication for large matrices. NumPy is optimized for such operations to do the computations efficiently.

In [2]:
import numpy as np
from numpy import random as rd

In [4]:
x1 = rd.randint(100, 1000)
x1

514

Let's say we want to create random arrays in particular shapes and size.

In [6]:
x1 = rd.randint(100, 1000, size = 10)
x1

array([766, 658, 264, 751, 320, 548, 406, 916, 658, 752])

We can check the shape of this array as well.

In [8]:
x1.shape

(10,)

We can reshape this array as well.

In [10]:
x1 = x1.reshape(1, 10)
x1.shape

(1, 10)

We can create multi-dimensional arrays as well.

In [12]:
x2 = rd.randint(100, 1000, size = (3,4))
x2

array([[250, 925, 941, 368],
       [406, 397, 261, 545],
       [861, 651, 325, 273]])

In [14]:
x3 = rd.randint(100, 1000, size = (4,3,4))
x3

array([[[111, 821, 928, 148],
        [450, 772, 616, 258],
        [792, 869, 257, 377]],

       [[875, 120, 235, 684],
        [426, 916, 163, 114],
        [482, 226, 830, 858]],

       [[280, 418, 415, 296],
        [436, 277, 374, 690],
        [510, 390, 241, 895]],

       [[650, 439, 618, 877],
        [401, 377, 495, 979],
        [851, 338, 369, 171]]])

We can reshape arrays to any shape while making sure that the product of dimensions remain same.

In [16]:
x3.reshape(12,4)

array([[111, 821, 928, 148],
       [450, 772, 616, 258],
       [792, 869, 257, 377],
       [875, 120, 235, 684],
       [426, 916, 163, 114],
       [482, 226, 830, 858],
       [280, 418, 415, 296],
       [436, 277, 374, 690],
       [510, 390, 241, 895],
       [650, 439, 618, 877],
       [401, 377, 495, 979],
       [851, 338, 369, 171]])

# Indexing
Let's say we want to access all the elements in the array or the givend data. We can use indexing to do that.

In [19]:
x4 = rd.randint(100, 1000, size = (5,4))
x4

array([[252, 881, 988, 708],
       [589, 901, 391, 990],
       [672, 370, 639, 351],
       [966, 817, 357, 225],
       [748, 802, 876, 533]])

In [21]:
# To access row 1
x4[0]

array([252, 881, 988, 708])

In [23]:
# To access first 2 rows
x4[0:2]

array([[252, 881, 988, 708],
       [589, 901, 391, 990]])

In [25]:
# To access all rows in the NumPy array
x4[:]

array([[252, 881, 988, 708],
       [589, 901, 391, 990],
       [672, 370, 639, 351],
       [966, 817, 357, 225],
       [748, 802, 876, 533]])

In [27]:
# Steps or Jumps
x4[::2]

array([[252, 881, 988, 708],
       [672, 370, 639, 351],
       [748, 802, 876, 533]])

In [29]:
# To access all rows and the first column of each row
x4[:, 0]

array([252, 589, 672, 966, 748])

In [31]:
# Accessing all rows and first two columns
x4[:, 0:2]

array([[252, 881],
       [589, 901],
       [672, 370],
       [966, 817],
       [748, 802]])

## Range Function in NumPy

We can create NumPy arrays using range functions as well.

arange() functions creates an arrays of numbers

In [36]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [43]:
a1 = np.arange(10, 22)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [46]:
a1.shape

(12,)

In [50]:
a1 = a1.reshape(6,2)
a1

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [52]:
a1.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [56]:
# To create an array of Zeros
a2 = np.zeros((2,3))
a2

array([[0., 0., 0.],
       [0., 0., 0.]])

By default, NumPy will have floating type of values in the array.
However, we can have integer type of values in the array as well by mentioning the data type as 'int'.

In [61]:
a3 = np.zeros((2,3), dtype = 'int')
a3

array([[0, 0, 0],
       [0, 0, 0]])

In [65]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [73]:
# Identity matrix
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

We can create an array with certain number of partitions between two numbers using linspace() function.

In [78]:
ls1 = np.linspace(0, 10, num = 5)
ls1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [80]:
ls2 = np.linspace(0, 100, 11)
ls2

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [82]:
a1 = np.random.randint(0, 100, size = 10)
a1

array([54, 20, 46, 70, 66, 97, 11, 68, 89, 11])

In [84]:
np.max(a1)

97

In [86]:
np.min(a1)

11

In [88]:
np.mean(a1)

53.2

In [90]:
np.std(a1)

29.294368059406914

In [92]:
np.floor([1.2, 1.6])

array([1., 1.])

In [94]:
np.ceil([1.2, 1.6])

array([2., 2.])

In [96]:
np.trunc([1.2, 1.6])

array([1., 1.])

In [98]:
np.round([1.2, 1.6])

array([1., 2.])

In [100]:
np.round([1.33453], 2)

array([1.33])

## Concatenating the Matrices

In [103]:
n1 = rd.randint(10, 20, size = (4,3))
n2 = rd.randint(10, 20, size = (4,3))

In [105]:
# Concatenating along the rows
np.concatenate([n1, n2])

array([[14, 10, 15],
       [14, 19, 12],
       [17, 19, 14],
       [11, 12, 19],
       [13, 17, 12],
       [13, 11, 17],
       [18, 12, 15],
       [15, 18, 18]])

In [107]:
# Concatenating along the columns
np.concatenate([n1, n2], axis = 1)

array([[14, 10, 15, 13, 17, 12],
       [14, 19, 12, 13, 11, 17],
       [17, 19, 14, 18, 12, 15],
       [11, 12, 19, 15, 18, 18]])

We can also use functions vstack() and hstack() to achieve the same results.

In [112]:
n3 = np.vstack([n1, n2])
n3

array([[14, 10, 15],
       [14, 19, 12],
       [17, 19, 14],
       [11, 12, 19],
       [13, 17, 12],
       [13, 11, 17],
       [18, 12, 15],
       [15, 18, 18]])

In [114]:
n4 = np.hstack([n1, n2])
n4

array([[14, 10, 15, 13, 17, 12],
       [14, 19, 12, 13, 11, 17],
       [17, 19, 14, 18, 12, 15],
       [11, 12, 19, 15, 18, 18]])

We can split an array into two parts along an axis. This can be useful to split the data into training and testing sets.

In [120]:
np.split(n3, 2, axis = 0)

[array([[14, 10, 15],
        [14, 19, 12],
        [17, 19, 14],
        [11, 12, 19]]),
 array([[13, 17, 12],
        [13, 11, 17],
        [18, 12, 15],
        [15, 18, 18]])]

In [122]:
# Minimum value in whole array
n4.min()

10

In [126]:
# Returns an array of Minimum value in every column
n4.min(axis = 0)

array([11, 10, 12, 13, 11, 12])

In [130]:
# Returns an array of minimum value in every row
n4.min(axis = 1)

array([10, 11, 12, 11])

In [136]:
np.median(n4, axis = 1)

array([13.5, 13.5, 16. , 16.5])

In [138]:
np.std(n4, axis = 1)

array([2.21735578, 2.80871659, 2.40947205, 3.09569594])

In [148]:
# Returns True where value is equal to 10
np.equal(n4, 10)

array([[False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [150]:
np.greater_equal(n4, 10)

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [152]:
np.less_equal(n4, 10)

array([[False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [154]:
np.sort(n4)

array([[10, 12, 13, 14, 15, 17],
       [11, 12, 13, 14, 17, 19],
       [12, 14, 15, 17, 18, 19],
       [11, 12, 15, 18, 18, 19]])